# Importação de bibliotecas e dados

In [42]:
import pandas as pd
import numpy as np

In [43]:
campeonatos = pd.read_csv('campeonatos_gauchos.csv', sep=',')
times = pd.read_csv('times_gauchos.csv', sep=',')
cidades = pd.read_csv('cidades_gauchas.csv')
pib = pd.read_csv('pib_cidades_gauchas.csv').rename(columns={'Posição' : 'Posicao'})
idh = pd.read_csv('idh_cidades_gauchas.csv').rename(columns={'Posição' : 'Posicao'})

In [44]:
campeonatos.head(10)

,Edicao,Ano,Primeiro,Segundo,Terceiro,Quarto,Artilheiro,N_de_gols
0,1ª,1919(detalhes),Brasil de Pelotas (1),Grêmio,—,—,ProençaBrasil de Pelotas,3
1,2ª,1920(detalhes),Guarany de Bagé (1),Grêmio,Uruguaiana,—,GreccoGuarany de Bagé,2
2,3ª,1921(detalhes),Grêmio (1),Riograndense,Brasil de Pelotas,Uruguaiana,MosquitoRiograndense,3
3,4ª,1922(detalhes),Grêmio (2),Guarani de Alegrete,Guarany de Cruz Alta,Bagé,LagartoGrêmio,5
4,5ª,1925(detalhes),Bagé (1),Grêmio,Guarany de Cruz Alta,Grêmio Santanense,PascoalitoBagé,?
5,6ª,1926(detalhes),Grêmio (3),Guarany de Bagé,Guarany-CS,Independente,CoróGrêmio,?
6,7ª,1927(detalhes),Internacional (1),Bagé,14 de Julho,Nacional-SL,BarrosInternacional,?
7,8ª,1928(detalhes),Americano-RS (1),Bagé,Gaúcho,Guarany de Rosário,JoãozinhoAmericano-RS,?
8,9ª,1929(detalhes),Cruzeiro-RS [d] (1),Guarany de Bagé,Riograndense,Ferro Carril,NestorCruzeiro-RS,?
9,10ª,1930(detalhes),Pelotas (1),Grêmio,Novo Hamburgo,—,MarcialPelotas,?

In [45]:
times.head(5)

,Apelido,Nome,Cidade,Fundacao
0,12 Horas,Esporte Clube 12 Horas,Porto Alegre,14/08/2001
1,14 de Julho de Passo Fundo,Grêmio Esportivo e Recreativo 14 de Julho,Passo Fundo,27/06/1921
2,15 de Campo Bom,Clube 15 de Novembro,Campo Bom,15/11/1911
3,Aimoré,Clube Esportivo Aimoré,São Leopoldo,26/03/1936
4,Americano,Sport Club Americano,Porto Alegre,04/07/1912

In [46]:
cidades.head(5)

           Cidade Populacao_2010 Populacao_2021  Microrregioes   Mesorregioes
0    Porto Alegre      1 450 555      1 492 530   Porto Alegre  Metropolitana
1   Caxias do Sul        437 889        523 716  Caxias do Sul       Nordeste
2          Canoas        323,827        349 728   Porto Alegre  Metropolitana
3         Pelotas        328,275        343 826        Pelotas        Sudeste
4        Gravataí        255 660        285 564   Porto Alegre  Metropolitana

# Tratamento dos dados

In [47]:
campeonatos[['Primeiro', 'Numero']] = campeonatos['Primeiro'].str.split(' \(', expand=True)
campeonatos['Primeiro'] = campeonatos['Primeiro'].map(lambda x: x[:x.find('[d]')] if '[d]' in x else x).map(lambda x: x[:x.find('-RS')] if '-RS' in x else x)
#campeonatos.iloc[8,2][:campeonatos.iloc[8,2].find('[d]')] 
#print('[d]' in campeonatos.iloc[8,2], campeonatos.iloc[8,2].find('[d]'),campeonatos.iloc[8,2][:13])
campeonatos['Edicao'] = campeonatos['Edicao'].str.extract(r'(\d+)', expand=False)
campeonatos['Ano'] = campeonatos['Ano'].str.extract(r'(\d+)', expand=False)
times['Apelido'] = times['Apelido'].str.normalize('NFKD')
#campeonatos['Primeiro'] = campeonatos['Primeiro'].str.normalize('NFKC')
#campeonatos['Primeiro'] = campeonatos['Primeiro'].str.encode('utf-8')
#times['Apelido'] = times['Apelido'].str.encode('utf-8')
#campeonatos = campeonatos.drop(columns=['Numero'])
#campeonatos['Ano'] = campeonatos['Ano'].str.replace(r'[(detalhes)]', '')
del campeonatos['Numero']
campeonatos.head(10)

,Edicao,Ano,Primeiro,Segundo,Terceiro,Quarto,Artilheiro,N_de_gols
0,1,1919,Brasil de Pelotas,Grêmio,—,—,ProençaBrasil de Pelotas,3
1,2,1920,Guarany de Bagé,Grêmio,Uruguaiana,—,GreccoGuarany de Bagé,2
2,3,1921,Grêmio,Riograndense,Brasil de Pelotas,Uruguaiana,MosquitoRiograndense,3
3,4,1922,Grêmio,Guarani de Alegrete,Guarany de Cruz Alta,Bagé,LagartoGrêmio,5
4,5,1925,Bagé,Grêmio,Guarany de Cruz Alta,Grêmio Santanense,PascoalitoBagé,?
5,6,1926,Grêmio,Guarany de Bagé,Guarany-CS,Independente,CoróGrêmio,?
6,7,1927,Internacional,Bagé,14 de Julho,Nacional-SL,BarrosInternacional,?
7,8,1928,Americano,Bagé,Gaúcho,Guarany de Rosário,JoãozinhoAmericano-RS,?
8,9,1929,Cruzeiro,Guarany de Bagé,Riograndense,Ferro Carril,NestorCruzeiro-RS,?
9,10,1930,Pelotas,Grêmio,Novo Hamburgo,—,MarcialPelotas,?

In [48]:
campeonatos['Segundo'] = campeonatos['Segundo'].map(lambda x: x[:max(map(lambda y: x.find(y) if y in x else 0, ['[a]','[b]', '[c]', '[d]']))] if ('[a]' in x) or ('[b]' in x) or ('[c]' in x) or ('[d]' in x)  else x).map(lambda x: x[:x.find('-RS')] if '-RS' in x else x)
campeonatos['Terceiro'] = campeonatos['Terceiro'].map(lambda x: x[:max(map(lambda y: x.find(y) if y in x else 0, ['[a]','[b]', '[c]', '[d]']))] if ('[a]' in x) or ('[b]' in x) or ('[c]' in x) or ('[d]' in x)  else x).map(lambda x: x[:x.find('-RS')] if '-RS' in x else x)
campeonatos['Quarto'] = campeonatos['Quarto'].map(lambda x: x[:max(map(lambda y: x.find(y) if y in x else 0, ['[a]','[b]', '[c]', '[d]']))] if ('[a]' in x) or ('[b]' in x) or ('[c]' in x) or ('[d]' in x)  else x).map(lambda x: x[:x.find('-RS')] if '-RS' in x else x)
#max(list(map(lambda x: a.find(str(x)), ['[a]','[b]', '[c]', '[d]'])))

In [49]:
campeonatos.iloc[2,3] = "Riograndense-SM"
campeonatos.iloc[[8,10,15,17,19,20],4 ] = "Riograndense-SM"
campeonatos.iloc[16,5] = "Riograndense-SM"
campeonatos.iloc[18,2] = "Riograndense-RG"
campeonatos.iloc[[16,17,25],3] = "Riograndense-RG"
campeonatos.iloc[36,4] = "Riograndense-RG"
times.iloc[50,0] = "Riograndense-RG"
times.iloc[51,0] = "Riograndense-SM"
times.iloc[17,0] = "Esportivo"
times.iloc[2,0] = "15 de Novembro"
times.iloc[1,0] = "14 de Julho"

In [50]:
print(times.iloc[21,0], 'Glória de Vacaria')

Glória de Vacaria Glória de Vacaria

In [51]:
times['Apelido'] = times['Apelido'].str.replace('Internacional de Santa Maria', 'Inter SM')
times['Apelido'] = times['Apelido'].str.replace('Glória de Vacaria', 'Glória')
times['Apelido'] = times['Apelido'].replace({'Atlético de Carazinho' : 'Atlético Carazinho'})

In [52]:
times.head(50)

,Apelido,Nome,Cidade,Fundacao
0,12 Horas,Esporte Clube 12 Horas,Porto Alegre,14/08/2001
1,14 de Julho,Grêmio Esportivo e Recreativo 14 de Julho,Passo Fundo,27/06/1921
2,15 de Novembro,Clube 15 de Novembro,Campo Bom,15/11/1911
3,Aimoré,Clube Esportivo Aimoré,São Leopoldo,26/03/1936
4,Americano,Sport Club Americano,Porto Alegre,04/07/1912
5,Armour,Armour Futebol Clube,Santana do Livramento,17/06/1917
6,Atlético Carazinho,Clube Atlético de Carazinho,Carazinho,01/07/1970
7,Avenida,Esporte Clube Avenida,Santa Cruz do Sul,06/01/1944
8,Bagé,Grêmio Esportivo Bagé,Bagé,05/08/1920
9,Brasil de Farroupilha,Sociedade Esportiva Recreativa e Cultural Brasil,Farroupilha,15/01/1939
10,Brasil de Pelotas,Grêmio Esportivo Brasil,Pelotas,07/09/1911
11,Cachoeira,Cachoeira Futebol Clube,Cachoeira do Sul,24/02/1914
12,Canoas,Canoas Sport Club,Canoas,23/01/1998
13,Caxias,Sociedade Esportiva e Recreativa Caxias do Sul,Caxias do Sul,10/04/1935
14,Cruz Alta,Sociedade Esportiva e Recreativa Cruz Alta,Cruz Alta,26/09/2007
15,Cruzeiro,Esporte Clube Cruzeiro,Cachoeirinha,14/07/1913
16,Elite,Elite Clube Desportivo,Santo Ângelo,30/09/1921
17,Esportivo,Clube Esportivo Bento Gonçalves,Bento Gonçalves,28/08/1919
18,Farroupilha,Grêmio Atlético Farroupilha,Pelotas,26/04/1926
19,Gaúcho,Sport Club Gaúcho,Passo Fundo,12/05/1918
20,Glória de Carazinho,Grêmio Atlético Glória,Carazinho,18/06/1933
21,Glória,Grêmio Esportivo Glória,Vacaria,15/11/1956
22,Grêmio,Grêmio Foot-Ball Porto Alegrense,Porto Alegre,15/09/1903
23,Grêmio Santanense,Grêmio Foot-Ball Santanense,Santana do Livramento,11/06/1913
24,Guarani de Alegrete,Guarani Futebol Clube,Alegrete,20/09/1912
25,Guarani de Venâncio Aires,Esporte Clube Guarani,Venâncio Aires,06/01/1944
26,Guarany de Bagé,Guarany Futebol Clube,Bagé,19/04/1907
27,Guarany de Cachoeira do Sul,Guarany Futebol Clube,Cachoeira do Sul,1917
28,Guarany de Camaquã,Guarany Futebol Clube,Camaquã,16/06/1946
29,Guarani de Venâncio Aires,Esporte Clube Guarani,Venâncio Aires,06/01/1944
30,Igrejinha,Esporte Clube Igrejinha,Igrejinha,26/04/1930
31,Internacional,Sport Club Internacional,Porto Alegre,04/04/1909
32,Inter SM,Esporte Clube Internacional,Santa Maria,16/05/1928
33,Juventude,Esporte Clube Juventude,Caxias do Sul,29/06/1913
34,Lajeadense,Clube Esportivo Lajeadense,Lajeado,23/04/1911
35,Marau,Futebol Clube Marau,Marau,21/06/2013
36,Nacional,Esporte Clube Nacional,Cruz Alta,17/03/1941
37,Nova Prata,Associação Nova Prata de Esportes Cultura e Lazer,Nova Prata,10/04/2003
38,Novo Hamburgo,Esporte Clube Novo Hamburgo,Novo Hamburgo,01/05/1911
39,Novo Horizonte,Esporte Clube Novo Horizonte,Esteio,28/12/2008
40,Palmeirense,Esporte Clube Palmeirense,Palmeira das Missões,27/05/1919
41,Panambi,Sociedade Esportiva e Recreativa Panambi,Panambi,01/01/2004
42,Passo Fundo,Esporte Clube Passo Fundo,Passo Fundo,10/01/1986
43,Pelotas,Esporte Clube Pelotas,Pelotas,11/10/1908
44,Porto Alegre,Porto Alegre Futebol Clube,Porto Alegre,10/06/2003
45,Pradense,Clube Atlético Pradense,Antônio Prado,06/11/1911
46,PRS,Players RS Futebol Clube,Garibaldi,2015
47,Real,Real Sport Club,Capão da Canoa,2005
48,Renner,Grêmio Esportivo Renner,Porto Alegre,27/07/1931
49,Rio Grande,Sport Club Rio Grande,Rio Grande,19/07/1900

In [53]:
campeonatos['Segundo'] = campeonatos['Segundo'].str.replace('Ypiranga de Erechim', 'Ypiranga')
campeonatos['Terceiro'] = campeonatos['Terceiro'].str.replace('Ypiranga de Erechim', 'Ypiranga')
campeonatos['Quarto'] = campeonatos['Quarto'].str.replace('Ypiranga de Erechim', 'Ypiranga')
campeonatos['Terceiro'] = campeonatos['Terceiro'].str.replace('Inter de Santa Maria', 'Inter SM')
campeonatos['Quarto'] = campeonatos['Quarto'].str.replace('Inter de Santa Maria', 'Inter SM')

In [54]:
Apelido_new = ['Riograndense-PF', 'Riograndense-CA', 'Esperança', 'Guarany de Cruz Alta', 'Uruguaiana', 'Independente', 
                'Ferro Carril', 'Universal', 'Guarany de Rosário', 'Guarany-CS', 'Nacional-SL', 'Fluminense', 'Cruzeiro-SG',
                'Nacional-CA', 'Ta-Guá', 'Inter de São Borja', 'Guarany/Cotriel', 'Pedrabranca', 'Ipiranga de Sarandi',
                'Tresmaiense', 'Juventus de Santa Rosa', 'Sapiranga', 'Guarany de Garibaldi', 'Estrela', 'Taquariense',
                'Dínamo', 'Veronese', 'Encantado', 'Alegrete', 'Pratense', 'Juventude de Guaporé', 'Botafogo', 'Ferroviário',
                'Bancário', 'Santa Rosa', 'Atlântico', 'Inter de Rosário', 'Taquarense', 'Veterano', 'Pedro Osório', 'São Gabriel']

Nome_new = ['Riograndense Futebol Clube', 'Grêmio Riograndense Futebol Clube', 'Football-Club Esperança', 'Sport Club Guarany', 
                'Esporte Clube Uruguaiana', 'Independente Futebol Clube', 'Esporte Clube Ferro Carril', 'Sport Club Universal', 
                'Sport Club Guarany', 'Guarany Futebol Clube', 'Grêmio Esportivo Nacional', 'Fluminense Futebol Clube',
                'Esporte Clube Cruzeiro', 'Esporte Clube Nacional', 'Tabajara-Guaíba Futebol Clube', 'Sport Club Internacional',
                'Clube Atlético Guarany', 'Pedrabranca Futebol Clube', 'Esporte Clube Ipiranga Sarandi', 
                'Associação Tresmaiense de Esportes', 'Juventus Atlético Clube', 'Associação Esportiva Sapiranga',
                'Grêmio Atlético Guarany', 'Estrela Futebol Clube', 'Grêmio Esportivo Taquariense', 'Dínamo Futebol Clube',
                'Grêmio Esportivo Veronese', 'Esporte Clube Encantado', 'Associação Atlética Alegrete', 'Grêmio Esportivo Pratense',
                'Grêmio Esportivo Juventude', 'Botafogo Foot-Ball Club', 'Grêmio Sportivo Ferroviário', 'Clube Atlético Bancário',
                'Associação Santa Rosa de Esportes', 'Clube Esportivo e Recreativo Atlântico', 'Atlético Clube Internacional',
                'Sport Club Taquarense', 'Veterano Futebol Clube', 'Grêmio Esportivo Pedro Osório', 
                'Sociedade Esportiva e Recreativa São Gabriel']

Cidade_new = ['Passo Fundo', 'Cruz Alta', 'Novo Hamburgo', 'Cruz Alta', 'Uruguaiana', 'Santana do Livramento', 'Uruguaiana', 
                'Uruguaiana', 'Rosário do Sul' , 'Cachoeira do Sul', 'São Leopoldo', 'Santana do Livramento', 'São Gabriel', 
                'Cruz Alta', 'Getúlio Vargas', 'São Borja', 'Espumoso', 'Alvorada', 'Sarandi', 'Três de Maio', 'Santa Rosa', 
                'Sapiranga', 'Garibaldi', 'Estrela', 'Taquari', 'Santa Rosa', 'Canoas', 'Encantado', 'Alegrete', 'Nova Prata',
                'Guaporé', 'São Gabriel', 'Bagé', 'Pelotas', 'Santa Rosa', 'Erechim', 'Rosário do Sul', 'Taquara', 'Carazinho',
                'Tupanciretã', 'São Gabriel']

Fundacao_new = ['08/08/1925', '30/07/1929', '10/05/1914', '20/09/1913', '19/05/1912', '07/09/1921', '01/03/1916', '01/01/1925', 
                    '03/02/1909', 1917, '28/04/1915', '23/03/1936','31/12/1951','17/03/1941', '27/01/1964', '07/07/1931', 
                    '01/07/1956', '09/04/2001', '14/04/1947', '13/01/1992', '12/03/1951','07/08/1945','14/08/1940', '17/11/1931', 
                    '03/08/1940', '20/09/1970', '01/05/1942', '21/04/1942', '20/02/1973', '11/01/1955', '02/01/1941', '13/05/1936',
                    '06/05/1933', '10/12/1925', '10/03/1973', '20/09/1915', '09/07/1938', '30/11/1911', '25/10/1933', '21/03/1943', 
                    '01/05/1979']

#times_new = pd.DataFrame({'Apelido': Apelido_new, 'Nome' : Nome_new, 'Cidade' : Cidade_new, 'Fundacao': Fundacao_new})
times = pd.concat([times, pd.DataFrame({'Apelido': Apelido_new, 'Nome' : Nome_new, 'Cidade' : Cidade_new, 'Fundacao': Fundacao_new})], ignore_index=True)
times.tail(5)

,Apelido,Nome,Cidade,Fundacao
107,Inter de Rosário,Atlético Clube Internacional,Rosário do Sul,09/07/1938
108,Taquarense,Sport Club Taquarense,Taquara,30/11/1911
109,Veterano,Veterano Futebol Clube,Carazinho,25/10/1933
110,Pedro Osório,Grêmio Esportivo Pedro Osório,Tupanciretã,21/03/1943
111,São Gabriel,Sociedade Esportiva e Recreativa São Gabriel,São Gabriel,01/05/1979

In [55]:
campeonatos['Primeiro'] = campeonatos['Primeiro'].str.normalize('NFKC').str.replace(' ', '', n=1).map(lambda x: x[:-1] if x[-1] == ' ' else x)
campeonatos['Segundo'] = campeonatos['Segundo'].str.normalize('NFKC').str.replace(' ', '', n=1).map(lambda x: x[:-1] if x[-1] == ' ' else x)
campeonatos['Terceiro'] = campeonatos['Terceiro'].str.normalize('NFKC').str.replace(' ', '', n=1).map(lambda x: x[:-1] if x[-1] == ' ' else x)
campeonatos['Quarto'] = campeonatos['Quarto'].str.normalize('NFKC').str.replace(' ', '', n=1).map(lambda x: x[:-1] if x[-1] == ' ' else x)
times['Apelido'] = times['Apelido'].str.normalize('NFKC')

In [56]:
times.duplicated(subset=['Nome', 'Cidade']).values

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [57]:
#print(list(times.duplicated(subset=['Nome', 'Cidade'])).index(True))
valores_duplicados = np.array(times.duplicated(subset=['Nome', 'Cidade'], keep = 'last'))
np.where(valores_duplicados == True)

(array([25, 27, 36], dtype=int64),)

In [58]:
times = times.drop_duplicates(subset=['Nome', 'Cidade'], keep = 'last')

In [59]:
#pd.set_option('max_rows', 120)
times.sort_values(by=['Apelido'], inplace = True, ignore_index=True)
times.tail(5)

,Apelido,Nome,Cidade,Fundacao
104,Uruguaiana,Esporte Clube Uruguaiana,Uruguaiana,19/05/1912
105,Veranópolis,Veranópolis Esporte Clube Recreativo e Cultural,Veranópolis,15/01/1992
106,Veronese,Grêmio Esportivo Veronese,Canoas,01/05/1942
107,Veterano,Veterano Futebol Clube,Carazinho,25/10/1933
108,Ypiranga,Ypiranga Futebol Clube,Erechim,18/08/1924

In [60]:
print(times.iloc[79, 0],campeonatos.iloc[7,5], times.iloc[73, 0] == campeonatos.iloc[24,4])

Riograndense-SM Guarany de Rosário False

In [61]:
#pd.set_option('max_rows', 120)
campeonatos = campeonatos .\
    merge(times, how='left', left_on='Primeiro', right_on = "Apelido").drop(columns=['Apelido', 'Nome', 'Fundacao']).rename(columns={"Cidade": "Cidade_Primeiro"}) .\
    merge(times, how='left', left_on='Segundo', right_on = "Apelido").drop(columns=['Apelido', 'Nome', 'Fundacao']).rename(columns={"Cidade": "Cidade_Segundo"}) .\
    merge(times, how='left', left_on='Terceiro', right_on = "Apelido").drop(columns=['Apelido', 'Nome', 'Fundacao']).rename(columns={"Cidade": "Cidade_Terceiro"}) .\
    merge(times, how='left', left_on='Quarto', right_on = "Apelido").drop(columns=['Apelido', 'Nome', 'Fundacao']).rename(columns={"Cidade": "Cidade_Quarto"})
campeonatos.head(5)

,Edicao,Ano,Primeiro,Segundo,Terceiro,Quarto,Artilheiro,N_de_gols,Cidade_Primeiro,Cidade_Segundo,Cidade_Terceiro,Cidade_Quarto
0,1,1919,Brasil de Pelotas,Grêmio,—,—,ProençaBrasil de Pelotas,3,Pelotas,Porto Alegre,NaN,NaN
1,2,1920,Guarany de Bagé,Grêmio,Uruguaiana,—,GreccoGuarany de Bagé,2,Bagé,Porto Alegre,Uruguaiana,NaN
2,3,1921,Grêmio,Riograndense-SM,Brasil de Pelotas,Uruguaiana,MosquitoRiograndense,3,Porto Alegre,Santa Maria,Pelotas,Uruguaiana
3,4,1922,Grêmio,Guarani de Alegrete,Guarany de Cruz Alta,Bagé,LagartoGrêmio,5,Porto Alegre,Alegrete,Cruz Alta,Bagé
4,5,1925,Bagé,Grêmio,Guarany de Cruz Alta,Grêmio Santanense,PascoalitoBagé,?,Bagé,Porto Alegre,Cruz Alta,Santana do Livramento

In [62]:
campeonatos.iloc[100,2]

'Grêmio'

In [63]:
campeonatos['N_de_gols'] = campeonatos['N_de_gols'].replace({'?' : None})
campeonatos['Terceiro'] = campeonatos['Terceiro'].replace({'—' : None})
campeonatos['Quarto'] = campeonatos['Quarto'].replace({'—' : None})
campeonatos.head(5)

,Edicao,Ano,Primeiro,Segundo,Terceiro,Quarto,Artilheiro,N_de_gols,Cidade_Primeiro,Cidade_Segundo,Cidade_Terceiro,Cidade_Quarto
0,1,1919,Brasil de Pelotas,Grêmio,None,None,ProençaBrasil de Pelotas,3,Pelotas,Porto Alegre,NaN,NaN
1,2,1920,Guarany de Bagé,Grêmio,Uruguaiana,None,GreccoGuarany de Bagé,2,Bagé,Porto Alegre,Uruguaiana,NaN
2,3,1921,Grêmio,Riograndense-SM,Brasil de Pelotas,Uruguaiana,MosquitoRiograndense,3,Porto Alegre,Santa Maria,Pelotas,Uruguaiana
3,4,1922,Grêmio,Guarani de Alegrete,Guarany de Cruz Alta,Bagé,LagartoGrêmio,5,Porto Alegre,Alegrete,Cruz Alta,Bagé
4,5,1925,Bagé,Grêmio,Guarany de Cruz Alta,Grêmio Santanense,PascoalitoBagé,None,Bagé,Porto Alegre,Cruz Alta,Santana do Livramento

In [64]:
campeonatos.dtypes

Edicao             object
Ano                object
Primeiro           object
Segundo            object
Terceiro           object
Quarto             object
Artilheiro         object
N_de_gols          object
Cidade_Primeiro    object
Cidade_Segundo     object
Cidade_Terceiro    object
Cidade_Quarto      object
dtype: object

In [65]:
campeonatos.convert_dtypes().dtypes

Edicao             string
Ano                string
Primeiro           string
Segundo            string
Terceiro           string
Quarto             string
Artilheiro         string
N_de_gols          string
Cidade_Primeiro    string
Cidade_Segundo     string
Cidade_Terceiro    string
Cidade_Quarto      string
dtype: object

In [66]:
campeonatos.infer_objects().dtypes

Edicao             object
Ano                object
Primeiro           object
Segundo            object
Terceiro           object
Quarto             object
Artilheiro         object
N_de_gols          object
Cidade_Primeiro    object
Cidade_Segundo     object
Cidade_Terceiro    object
Cidade_Quarto      object
dtype: object

In [67]:
campeonatos = campeonatos.astype("category")
campeonatos = campeonatos.astype({'Edicao': np.uint8, 'Ano' : np.uint16, 'Artilheiro' : object})
campeonatos['N_de_gols'] = campeonatos['N_de_gols'].astype('float')
campeonatos['N_de_gols'] = campeonatos['N_de_gols'].astype('Int8')
campeonatos.dtypes

Edicao                uint8
Ano                  uint16
Primeiro           category
Segundo            category
Terceiro           category
Quarto             category
Artilheiro           object
N_de_gols              Int8
Cidade_Primeiro    category
Cidade_Segundo     category
Cidade_Terceiro    category
Cidade_Quarto      category
dtype: object

In [68]:
#pd.set_option('max_rows', 120)
campeonatos = campeonatos.drop_duplicates(subset=['Edicao', 'Ano'], keep = 'last')
campeonatos.head(5)

,Edicao,Ano,Primeiro,Segundo,Terceiro,Quarto,Artilheiro,N_de_gols,Cidade_Primeiro,Cidade_Segundo,Cidade_Terceiro,Cidade_Quarto
0,1,1919,Brasil de Pelotas,Grêmio,NaN,NaN,ProençaBrasil de Pelotas,3,Pelotas,Porto Alegre,NaN,NaN
1,2,1920,Guarany de Bagé,Grêmio,Uruguaiana,NaN,GreccoGuarany de Bagé,2,Bagé,Porto Alegre,Uruguaiana,NaN
2,3,1921,Grêmio,Riograndense-SM,Brasil de Pelotas,Uruguaiana,MosquitoRiograndense,3,Porto Alegre,Santa Maria,Pelotas,Uruguaiana
3,4,1922,Grêmio,Guarani de Alegrete,Guarany de Cruz Alta,Bagé,LagartoGrêmio,5,Porto Alegre,Alegrete,Cruz Alta,Bagé
4,5,1925,Bagé,Grêmio,Guarany de Cruz Alta,Grêmio Santanense,PascoalitoBagé,<NA>,Bagé,Porto Alegre,Cruz Alta,Santana do Livramento

In [69]:
times = times.astype("category")
times.dtypes

Apelido     category
Nome        category
Cidade      category
Fundacao    category
dtype: object

In [70]:
times.head(10)

,Apelido,Nome,Cidade,Fundacao
0,12 Horas,Esporte Clube 12 Horas,Porto Alegre,14/08/2001
1,14 de Julho,Grêmio Esportivo e Recreativo 14 de Julho,Passo Fundo,27/06/1921
2,15 de Novembro,Clube 15 de Novembro,Campo Bom,15/11/1911
3,A.E. São Borja,Associação Esportiva São Borja,São Borja,19/02/2009
4,Aimoré,Clube Esportivo Aimoré,São Leopoldo,26/03/1936
5,Alegrete,Associação Atlética Alegrete,Alegrete,20/02/1973
6,Americano,Sport Club Americano,Porto Alegre,04/07/1912
7,Armour,Armour Futebol Clube,Santana do Livramento,17/06/1917
8,Atlântico,Clube Esportivo e Recreativo Atlântico,Erechim,20/09/1915
9,Atlético Carazinho,Clube Atlético de Carazinho,Carazinho,01/07/1970

In [71]:
cidades['Cidade'] = cidades['Cidade'].str.normalize('NFKC').map(lambda x: x[1:] if x[0] == ' ' else x).map(lambda x: x[:-1] if x[-1] == ' ' else x)
cidades['Mesorregioes'] = cidades['Mesorregioes'].str.normalize('NFKC').map(lambda x: x[1:] if x[0] == ' ' else x).map(lambda x: x[:-1] if x[-1] == ' ' else x)
cidades['Microrregioes'] = cidades['Microrregioes'].str.normalize('NFKC').map(lambda x: x[1:] if x[0] == ' ' else x).map(lambda x: x[:-1] if x[-1] == ' ' else x)
cidades['Populacao_2010'] = cidades['Populacao_2010'].str.normalize('NFKC').str.replace(' ', '').str.replace(',', '').map(lambda x: None if '[3]' in x else x).astype(float).astype('Int64')
cidades['Populacao_2021'] = cidades['Populacao_2021'].str.normalize('NFKC').str.replace(' ', '').str.replace(',', '').astype('int64')

In [72]:
pib = pib.drop(pib.index[0])

In [73]:
pd.options.mode.chained_assignment = None
pib1 = pib[pib['Posicao'] == '1.1']
pib2 = pib[pib['Posicao'] == '2.1']
pib1['Localidade'] = pib1['Localidade'].str.normalize('NFKC').map(lambda x: x[1:] if x[0] == ' ' else x).map(lambda x: x[:-1] if x[-1] == ' ' else x)
pib2['Localidade'] = pib2['Localidade'].str.normalize('NFKC').map(lambda x: x[1:] if x[0] == ' ' else x).map(lambda x: x[:-1] if x[-1] == ' ' else x)

In [74]:
pib1 = pib1.drop(columns=['Posicao', 'Nome', '1999', '2000', '2001','2002','2003', 
                    '2004', '2005', '2006', '2007', '2008', '2009', '2011', '2012', 
                    '2013', '2014', '2015', '2016', '2017', '2018', 'Unidade', 'Multiplicador'])
pib2 = pib2.drop(columns=['Posicao', 'Nome', '1999', '2000', '2001','2002','2003', 
                    '2004', '2005', '2006', '2007', '2008', '2009', '2011', '2012', 
                    '2013', '2014', '2015', '2016', '2017', '2018', 'Unidade', 'Multiplicador'])

In [75]:
idh = idh.drop(idh.index[len(idh)-1]).drop(columns=['Posicao', 'Nome', 'Unidade', 'Multiplicador'])
idh['Localidade'] = idh['Localidade'].str.normalize('NFKC').map(lambda x: x[1:] if x[0] == ' ' else x).map(lambda x: x[:-1] if x[-1] == ' ' else x)

In [76]:
cidades = cidades .\
    merge(pib1, how='left', left_on='Cidade', right_on = "Localidade").drop(columns=['Localidade']).rename(columns={"2010": "PIB_2010", "2019" : "PIB_2019"}) .\
    merge(pib2, how='left', left_on='Cidade', right_on = "Localidade").drop(columns=['Localidade']).rename(columns={"2010": "PIB_per_capita_2010", "2019" : "PIB_per_capita_2019"}) .\
    merge(idh, how='left', left_on='Cidade', right_on = "Localidade").drop(columns=['Localidade']).rename(columns={"2010": "IDH_2010", "2000" : "IDH_2000","1991" : "IDH_1991"})

In [77]:
cidades['PIB_2010'] = cidades['PIB_2010'].map(lambda x: None if '-' in str(x) else x)
cidades['PIB_per_capita_2010'] = cidades['PIB_per_capita_2010'].map(lambda x: None if '-' in str(x) else x)
cidades['IDH_2010'] = cidades['IDH_2010'].map(lambda x: None if '-' in str(x) else x)
cidades['IDH_2000'] = cidades['IDH_2000'].map(lambda x: None if '-' in str(x) else x)
cidades['IDH_1991'] = cidades['IDH_1991'].map(lambda x: None if '-' in str(x) else x)

In [78]:
cidades.dtypes

Cidade                  object
Populacao_2010           Int64
Populacao_2021           int64
Microrregioes           object
Mesorregioes            object
PIB_2010                object
PIB_2019               float64
PIB_per_capita_2010     object
PIB_per_capita_2019    float64
IDH_1991                object
IDH_2000                object
IDH_2010                object
dtype: object

In [79]:
cidades = cidades.astype({'Cidade': 'category', 'Microrregioes': 'category', 'Mesorregioes': 'category'})
cidades = cidades.astype({'PIB_2010': 'float64', 'PIB_per_capita_2010': 'float64', 'IDH_1991': 'float64',
                            'IDH_2000': 'float64', 'IDH_2010' : 'float64'})
cidades.dtypes

Cidade                 category
Populacao_2010            Int64
Populacao_2021            int64
Microrregioes          category
Mesorregioes           category
PIB_2010                float64
PIB_2019                float64
PIB_per_capita_2010     float64
PIB_per_capita_2019     float64
IDH_1991                float64
IDH_2000                float64
IDH_2010                float64
dtype: object

In [80]:
times.to_csv(r'times_gauchos_tratado.csv', index = False, header=True,encoding = 'utf-8-sig')
campeonatos.to_csv(r'campeonatos_gauchos_tratado.csv', index = False, header=True,encoding = 'utf-8-sig')
cidades.to_csv(r'cidades_gauchas_tratado.csv', index = False, header=True,encoding = 'utf-8-sig')

In [81]:
times.head(10)

,Apelido,Nome,Cidade,Fundacao
0,12 Horas,Esporte Clube 12 Horas,Porto Alegre,14/08/2001
1,14 de Julho,Grêmio Esportivo e Recreativo 14 de Julho,Passo Fundo,27/06/1921
2,15 de Novembro,Clube 15 de Novembro,Campo Bom,15/11/1911
3,A.E. São Borja,Associação Esportiva São Borja,São Borja,19/02/2009
4,Aimoré,Clube Esportivo Aimoré,São Leopoldo,26/03/1936
5,Alegrete,Associação Atlética Alegrete,Alegrete,20/02/1973
6,Americano,Sport Club Americano,Porto Alegre,04/07/1912
7,Armour,Armour Futebol Clube,Santana do Livramento,17/06/1917
8,Atlântico,Clube Esportivo e Recreativo Atlântico,Erechim,20/09/1915
9,Atlético Carazinho,Clube Atlético de Carazinho,Carazinho,01/07/1970